FROM node:12
WORKDIR /usr/src/clean-node-api

COPY package.json /usr/src/clean-node-api/

RUN npm install

COPY . /usr/src/clean-node-api

RUN npm run build

EXPOSE 5050
EXPOSE 9222
# CMD [ "npm", "start" ]
# CMD [ "npm", "run", "debug" ]
